// <auto-generated />
using System;
using DockerImpliciteTest.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DockerImpliciteTest.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CategoryImageUpload", b =>
                {
                    b.Property<int>("CategoriesCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageUploadsImageUploadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesCategoryId", "ImageUploadsImageUploadId");

                    b.HasIndex("ImageUploadsImageUploadId");

                    b.ToTable("CategoryImageUpload");
                });

            modelBuilder.Entity("CategoryTest", b =>
                {
                    b.Property<int>("PosCategoriesCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostCategorieTestsTestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PosCategoriesCategoryId", "PostCategorieTestsTestId");

                    b.HasIndex("PostCategorieTestsTestId");

                    b.ToTable("CategoryTest");
                });

            modelBuilder.Entity("CategoryTest1", b =>
                {
                    b.Property<int>("NegCategorieTestsTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NegCategoriesCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NegCategorieTestsTestId", "NegCategoriesCategoryId");

                    b.HasIndex("NegCategoriesCategoryId");

                    b.ToTable("CategoryTest1");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = -1,
                            Name = "Mannen"
                        },
                        new
                        {
                            CategoryId = -2,
                            Name = "Vrouwen"
                        },
                        new
                        {
                            CategoryId = -3,
                            Name = "Jong"
                        },
                        new
                        {
                            CategoryId = -4,
                            Name = "Oud"
                        },
                        new
                        {
                            CategoryId = -5,
                            Name = "Positive"
                        },
                        new
                        {
                            CategoryId = -6,
                            Name = "Negative"
                        });
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.FaceReader", b =>
                {
                    b.Property<int>("FaceReaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FaceReaderId");

                    b.ToTable("FaceReaders");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.FaceReaderData", b =>
                {
                    b.Property<int>("FaceReaderDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Angry")
                        .HasColumnType("REAL");

                    b.Property<double>("Contempt")
                        .HasColumnType("REAL");

                    b.Property<double>("Disgusted")
                        .HasColumnType("REAL");

                    b.Property<int?>("FaceReaderId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Happy")
                        .HasColumnType("REAL");

                    b.Property<double>("Neutral")
                        .HasColumnType("REAL");

                    b.Property<double>("Sad")
                        .HasColumnType("REAL");

                    b.Property<double>("Scared")
                        .HasColumnType("REAL");

                    b.Property<double>("Surprised")
                        .HasColumnType("REAL");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("FaceReaderDataId");

                    b.HasIndex("FaceReaderId");

                    b.ToTable("FaceReaderData");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Fase", b =>
                {
                    b.Property<int>("FaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImgAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FaseId");

                    b.HasIndex("TestId");

                    b.ToTable("Fases");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.FaseTypeImage", b =>
                {
                    b.Property<int>("FaseTypeImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FaseTypeImageId");

                    b.HasIndex("FaseId");

                    b.HasIndex("ImageId");

                    b.ToTable("FaseTypeImages");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageUploadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.HasIndex("ImageUploadId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.ImageUpload", b =>
                {
                    b.Property<int>("ImageUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageUploadId");

                    b.ToTable("ImageUploads");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaceReaderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Participant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeLineResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResultId");

                    b.HasIndex("FaceReaderId");

                    b.HasIndex("TestId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TestId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("ImageUploadTest", b =>
                {
                    b.Property<int>("PosImageUploadsImageUploadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostUploadTestsTestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PosImageUploadsImageUploadId", "PostUploadTestsTestId");

                    b.HasIndex("PostUploadTestsTestId");

                    b.ToTable("ImageUploadTest");
                });

            modelBuilder.Entity("ImageUploadTest1", b =>
                {
                    b.Property<int>("NegImageUploadsImageUploadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NegUploadTestsTestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NegImageUploadsImageUploadId", "NegUploadTestsTestId");

                    b.HasIndex("NegUploadTestsTestId");

                    b.ToTable("ImageUploadTest1");
                });

            modelBuilder.Entity("CategoryImageUpload", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerImpliciteTest.Data.ImageUpload", null)
                        .WithMany()
                        .HasForeignKey("ImageUploadsImageUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryTest", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.Category", null)
                        .WithMany()
                        .HasForeignKey("PosCategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerImpliciteTest.Data.Test", null)
                        .WithMany()
                        .HasForeignKey("PostCategorieTestsTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryTest1", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.Test", null)
                        .WithMany()
                        .HasForeignKey("NegCategorieTestsTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerImpliciteTest.Data.Category", null)
                        .WithMany()
                        .HasForeignKey("NegCategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.FaceReaderData", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.FaceReader", null)
                        .WithMany("FaceReaderDatas")
                        .HasForeignKey("FaceReaderId");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Fase", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.Test", null)
                        .WithMany("Fases")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.FaseTypeImage", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.Fase", "Fase")
                        .WithMany("FaseTypeImages")
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerImpliciteTest.Data.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fase");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Image", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.ImageUpload", "ImageUpload")
                        .WithMany("Images")
                        .HasForeignKey("ImageUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageUpload");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Result", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.FaceReader", "FaceReader")
                        .WithMany()
                        .HasForeignKey("FaceReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerImpliciteTest.Data.Test", "Test")
                        .WithMany("Results")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaceReader");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("ImageUploadTest", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.ImageUpload", null)
                        .WithMany()
                        .HasForeignKey("PosImageUploadsImageUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerImpliciteTest.Data.Test", null)
                        .WithMany()
                        .HasForeignKey("PostUploadTestsTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImageUploadTest1", b =>
                {
                    b.HasOne("DockerImpliciteTest.Data.ImageUpload", null)
                        .WithMany()
                        .HasForeignKey("NegImageUploadsImageUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerImpliciteTest.Data.Test", null)
                        .WithMany()
                        .HasForeignKey("NegUploadTestsTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.FaceReader", b =>
                {
                    b.Navigation("FaceReaderDatas");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Fase", b =>
                {
                    b.Navigation("FaseTypeImages");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.ImageUpload", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DockerImpliciteTest.Data.Test", b =>
                {
                    b.Navigation("Fases");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
